"use client";

import * as React from "react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import { useParams } from "next/navigation";
import {
  Shield,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  User,
  Clock,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Code2,
  Play,
  Pause,
  Eye,
  Download,
  Flag,
  ThumbsUp,
  ThumbsDown,
  MessageSquare,
  Copy,
  Video,
  SkipBack,
  SkipForward,
  FileCode,
  Brain,
  Percent,
  Calendar,
  Mail,
  MoreVertical,
} from "lucide-react";
import { AnimatedButton, IconButton } from "@/components/ui/animated-button";
import { ThemeToggle } from "@/components/ui/theme-toggle";

interface CandidateSubmission {
  id: string;
  name: string;
  email: string;
  score: number;
  maxScore: number;
  duration: number;
  submittedAt: string;
  violations: Array<{
    type: string;
    timestamp: string;
    description: string;
    severity: "low" | "medium" | "high";
  }>;
  questions: Array<{
    id: string;
    title: string;
    score: number;
    maxScore: number;
    code: string;
    similarity: number;
  }>;
  llmSimilarity: {
    overall: number;
    sources: Array<{
      type: string;
      similarity: number;
      snippet: string;
    }>;
  };
}

const mockSubmission: CandidateSubmission = {
  id: "sub_123",
  name: "Bob Smith",
  email: "bob@email.com",
  score: 78,
  maxScore: 100,
  duration: 72,
  submittedAt: "2024-01-20T12:15:00",
  violations: [
    {
      type: "tab_switch",
      timestamp: "00:08:45",
      description: "Switched to another browser tab",
      severity: "medium",
    },
    {
      type: "copy",
      timestamp: "00:23:12",
      description: "Attempted to copy code",
      severity: "high",
    },
    {
      type: "fullscreen_exit",
      timestamp: "00:45:30",
      description: "Exited fullscreen mode",
      severity: "medium",
    },
  ],
  questions: [
    {
      id: "1",
      title: "Two Sum",
      score: 30,
      maxScore: 30,
      code: `function twoSum(nums: number[], target: number): number[] {
  const map = new Map<number, number>();
  for (let i = 0; i < nums.length; i++) {
    const complement = target - nums[i];
    if (map.has(complement)) {
      return [map.get(complement)!, i];
    }
    map.set(nums[i], i);
  }
  return [];
}`,
      similarity: 45,
    },
    {
      id: "2",
      title: "Valid Parentheses",
      score: 20,
      maxScore: 30,
      code: `function isValid(s: string): boolean {
  const stack: string[] = [];
  const pairs: Record<string, string> = {
    ')': '(',
    '}': '{',
    ']': '['
  };
  
  for (const char of s) {
    if (char in pairs) {
      if (stack.pop() !== pairs[char]) return false;
    } else {
      stack.push(char);
    }
  }
  return stack.length === 0;
}`,
      similarity: 72,
    },
    {
      id: "3",
      title: "Merge Two Sorted Lists",
      score: 28,
      maxScore: 40,
      code: `function mergeTwoLists(l1: ListNode | null, l2: ListNode | null): ListNode | null {
  const dummy = new ListNode(0);
  let current = dummy;
  
  while (l1 && l2) {
    if (l1.val <= l2.val) {
      current.next = l1;
      l1 = l1.next;
    } else {
      current.next = l2;
      l2 = l2.next;
    }
    current = current.next;
  }
  
  current.next = l1 || l2;
  return dummy.next;
}`,
      similarity: 38,
    },
  ],
  llmSimilarity: {
    overall: 52,
    sources: [
      {
        type: "GPT-4 Pattern",
        similarity: 72,
        snippet: "The Valid Parentheses solution shows patterns commonly generated by LLMs...",
      },
      {
        type: "LeetCode Solution",
        similarity: 65,
        snippet: "Similar to top-voted LeetCode solution for Two Sum problem...",
      },
      {
        type: "GitHub Copilot",
        similarity: 45,
        snippet: "Code structure suggests possible AI assistance in Merge Lists...",
      },
    ],
  },
};

export default function RecruiterReviewPage() {
  const params = useParams();
  const [selectedQuestion, setSelectedQuestion] = React.useState(0);
  const [isPlaying, setIsPlaying] = React.useState(false);
  const [currentTime, setCurrentTime] = React.useState(0);
  const [activeTab, setActiveTab] = React.useState<"code" | "video" | "similarity">("code");
  const totalVideoDuration = mockSubmission.duration * 60;

  const scorePercentage = (mockSubmission.score / mockSubmission.maxScore) * 100;

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  const severityColors = {
    low: "bg-yellow-500/20 text-yellow-500 border-yellow-500/30",
    medium: "bg-orange-500/20 text-orange-500 border-orange-500/30",
    high: "bg-red-500/20 text-red-500 border-red-500/30",
  };

  React.useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isPlaying) {
      interval = setInterval(() => {
        setCurrentTime((prev) => {
          if (prev >= totalVideoDuration) {
            setIsPlaying(false);
            return prev;
          }
          return prev + 1;
        });
      }, 100);
    }
    return () => clearInterval(interval);
  }, [isPlaying, totalVideoDuration]);

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border bg-background/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
          <div className="flex items-center gap-4">
            <Link
              href="/recruiter/dashboard"
              className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to Dashboard
            </Link>
          </div>
          <div className="flex items-center gap-3">
            <ThemeToggle />
            <AnimatedButton
              variant="outline"
              size="sm"
              icon={<Download className="h-4 w-4" />}
            >
              Export Report
            </AnimatedButton>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-7xl px-6 py-8">
        {/* Candidate Info Header */}
        <motion.div
          className="flex items-start justify-between"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="flex items-start gap-4">
            <div className="flex h-16 w-16 items-center justify-center rounded-full bg-gradient-to-br from-primary to-violet-500 text-xl font-bold text-white">
              {mockSubmission.name
                .split(" ")
                .map((n) => n[0])
                .join("")}
            </div>
            <div>
              <h1 className="text-2xl font-bold">{mockSubmission.name}</h1>
              <div className="mt-1 flex items-center gap-4 text-sm text-muted-foreground">
                <span className="flex items-center gap-1">
                  <Mail className="h-4 w-4" />
                  {mockSubmission.email}
                </span>
                <span className="flex items-center gap-1">
                  <Calendar className="h-4 w-4" />
                  {new Date(mockSubmission.submittedAt).toLocaleDateString()}
                </span>
                <span className="flex items-center gap-1">
                  <Clock className="h-4 w-4" />
                  {mockSubmission.duration} mins
                </span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <AnimatedButton
              variant="outline"
              size="sm"
              icon={<ThumbsDown className="h-4 w-4" />}
              className="text-destructive hover:bg-destructive/10"
            >
              Reject
            </AnimatedButton>
            <AnimatedButton
              variant="gradient"
              size="sm"
              icon={<ThumbsUp className="h-4 w-4" />}
            >
              Approve
            </AnimatedButton>
          </div>
        </motion.div>

        {/* Score & Stats Overview */}
        <div className="mt-8 grid gap-4 sm:grid-cols-4">
          <motion.div
            className="rounded-xl border border-border bg-card p-5"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <p className="text-sm text-muted-foreground">Total Score</p>
            <div className="mt-2 flex items-baseline gap-1">
              <span
                className={`text-3xl font-bold ${
                  scorePercentage >= 80
                    ? "text-emerald-500"
                    : scorePercentage >= 60
                    ? "text-yellow-500"
                    : "text-red-500"
                }`}
              >
                {mockSubmission.score}
              </span>
              <span className="text-muted-foreground">/ {mockSubmission.maxScore}</span>
            </div>
            <div className="mt-2 h-1.5 rounded-full bg-muted">
              <motion.div
                className={`h-full rounded-full ${
                  scorePercentage >= 80
                    ? "bg-emerald-500"
                    : scorePercentage >= 60
                    ? "bg-yellow-500"
                    : "bg-red-500"
                }`}
                initial={{ width: 0 }}
                animate={{ width: `${scorePercentage}%` }}
                transition={{ duration: 0.8 }}
              />
            </div>
          </motion.div>

          <motion.div
            className="rounded-xl border border-border bg-card p-5"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
          >
            <p className="text-sm text-muted-foreground">Violations</p>
            <div className="mt-2 flex items-center gap-2">
              <AlertTriangle
                className={`h-8 w-8 ${
                  mockSubmission.violations.length > 2
                    ? "text-destructive"
                    : mockSubmission.violations.length > 0
                    ? "text-yellow-500"
                    : "text-emerald-500"
                }`}
              />
              <span className="text-3xl font-bold">{mockSubmission.violations.length}</span>
            </div>
            <p className="mt-1 text-xs text-muted-foreground">
              {mockSubmission.violations.filter((v) => v.severity === "high").length} high
              severity
            </p>
          </motion.div>

          <motion.div
            className="rounded-xl border border-border bg-card p-5"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
          >
            <p className="text-sm text-muted-foreground">AI Similarity</p>
            <div className="mt-2 flex items-center gap-2">
              <Brain
                className={`h-8 w-8 ${
                  mockSubmission.llmSimilarity.overall > 60
                    ? "text-destructive"
                    : mockSubmission.llmSimilarity.overall > 40
                    ? "text-yellow-500"
                    : "text-emerald-500"
                }`}
              />
              <span className="text-3xl font-bold">
                {mockSubmission.llmSimilarity.overall}%
              </span>
            </div>
            <p className="mt-1 text-xs text-muted-foreground">LLM pattern detection</p>
          </motion.div>

          <motion.div
            className="rounded-xl border border-border bg-card p-5"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
          >
            <p className="text-sm text-muted-foreground">Questions Solved</p>
            <div className="mt-2 flex items-center gap-2">
              <Code2 className="h-8 w-8 text-primary" />
              <span className="text-3xl font-bold">
                {mockSubmission.questions.filter((q) => q.score > 0).length}/
                {mockSubmission.questions.length}
              </span>
            </div>
            <p className="mt-1 text-xs text-muted-foreground">
              {Math.round(
                (mockSubmission.questions.reduce((acc, q) => acc + q.score, 0) /
                  mockSubmission.questions.reduce((acc, q) => acc + q.maxScore, 0)) *
                  100
              )}
              % average
            </p>
          </motion.div>
        </div>

        {/* Cheat Timeline */}
        <motion.div
          className="mt-8"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
        >
          <h2 className="text-lg font-semibold">Violation Timeline</h2>
          <div className="mt-4 rounded-xl border border-border bg-card p-6">
            {/* Timeline Track */}
            <div className="relative h-16">
              <div className="absolute inset-x-0 top-1/2 h-1 -translate-y-1/2 rounded-full bg-muted" />

              {/* Time markers */}
              <div className="absolute inset-x-0 top-1/2 flex -translate-y-1/2 justify-between">
                {[0, 15, 30, 45, 60, 75].map((min) => (
                  <div key={min} className="flex flex-col items-center">
                    <div className="h-2 w-px bg-muted-foreground/30" />
                    <span className="mt-4 text-xs text-muted-foreground">{min}m</span>
                  </div>
                ))}
              </div>

              {/* Violation Markers */}
              {mockSubmission.violations.map((violation, i) => {
                const timeParts = violation.timestamp.split(":");
                const seconds =
                  parseInt(timeParts[0]) * 60 + parseInt(timeParts[1]);
                const percent = (seconds / totalVideoDuration) * 100;

                return (
                  <motion.div
                    key={i}
                    className="absolute top-1/2 -translate-x-1/2 -translate-y-1/2 cursor-pointer"
                    style={{ left: `${percent}%` }}
                    initial={{ scale: 0, y: -20 }}
                    animate={{ scale: 1, y: 0 }}
                    transition={{ delay: 0.7 + i * 0.1 }}
                    onClick={() => {
                      setCurrentTime(seconds);
                      setActiveTab("video");
                    }}
                  >
                    <div
                      className={`flex h-8 w-8 items-center justify-center rounded-full border-2 ${
                        severityColors[violation.severity]
                      } bg-card shadow-lg`}
                    >
                      <AlertTriangle className="h-4 w-4" />
                    </div>
                    <div
                      className={`absolute -top-12 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-lg border px-2 py-1 text-xs ${
                        severityColors[violation.severity]
                      }`}
                    >
                      {violation.type.replace("_", " ")}
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </motion.div>

        {/* Main Content Tabs */}
        <div className="mt-8 grid gap-6 lg:grid-cols-3">
          {/* Question Selector */}
          <motion.div
            className="rounded-xl border border-border bg-card"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.6 }}
          >
            <div className="border-b border-border p-4">
              <h3 className="font-semibold">Questions</h3>
            </div>
            <div className="divide-y divide-border">
              {mockSubmission.questions.map((question, i) => (
                <button
                  key={question.id}
                  className={`flex w-full items-center gap-3 p-4 text-left transition-colors ${
                    selectedQuestion === i
                      ? "bg-primary/10"
                      : "hover:bg-muted/50"
                  }`}
                  onClick={() => setSelectedQuestion(i)}
                >
                  <div
                    className={`flex h-8 w-8 items-center justify-center rounded-lg ${
                      question.score === question.maxScore
                        ? "bg-emerald-500/20 text-emerald-500"
                        : question.score >= question.maxScore * 0.7
                        ? "bg-yellow-500/20 text-yellow-500"
                        : "bg-red-500/20 text-red-500"
                    }`}
                  >
                    {i + 1}
                  </div>
                  <div className="flex-1">
                    <p className="font-medium text-sm">{question.title}</p>
                    <p className="text-xs text-muted-foreground">
                      {question.score}/{question.maxScore} pts
                    </p>
                  </div>
                  <div className="flex flex-col items-end gap-1">
                    <div
                      className={`flex items-center gap-1 text-xs ${
                        question.similarity > 60
                          ? "text-destructive"
                          : question.similarity > 40
                          ? "text-yellow-500"
                          : "text-emerald-500"
                      }`}
                    >
                      <Brain className="h-3 w-3" />
                      {question.similarity}%
                    </div>
                  </div>
                </button>
              ))}
            </div>
          </motion.div>

          {/* Main Content Area */}
          <motion.div
            className="lg:col-span-2 rounded-xl border border-border bg-card overflow-hidden"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.7 }}
          >
            {/* Tabs */}
            <div className="flex border-b border-border">
              {[
                { id: "code", label: "Code", icon: Code2 },
                { id: "video", label: "Recording", icon: Video },
                { id: "similarity", label: "AI Analysis", icon: Brain },
              ].map((tab) => (
                <button
                  key={tab.id}
                  className={`flex items-center gap-2 px-6 py-3 text-sm font-medium transition-colors ${
                    activeTab === tab.id
                      ? "border-b-2 border-primary text-primary"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                  onClick={() => setActiveTab(tab.id as typeof activeTab)}
                >
                  <tab.icon className="h-4 w-4" />
                  {tab.label}
                </button>
              ))}
            </div>

            <AnimatePresence mode="wait">
              {activeTab === "code" && (
                <motion.div
                  key="code"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="p-4"
                >
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <h4 className="font-semibold">
                        {mockSubmission.questions[selectedQuestion].title}
                      </h4>
                      <p className="text-sm text-muted-foreground">
                        Score: {mockSubmission.questions[selectedQuestion].score}/
                        {mockSubmission.questions[selectedQuestion].maxScore}
                      </p>
                    </div>
                    <IconButton variant="ghost">
                      <Copy className="h-4 w-4" />
                    </IconButton>
                  </div>
                  <pre className="overflow-x-auto rounded-lg bg-slate-950 p-4 text-sm">
                    <code className="text-slate-50">
                      {mockSubmission.questions[selectedQuestion].code}
                    </code>
                  </pre>
                </motion.div>
              )}

              {activeTab === "video" && (
                <motion.div
                  key="video"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                >
                  <div className="relative aspect-video bg-slate-900">
                    <div className="absolute inset-0 flex items-center justify-center">
                      <div className="text-center">
                        <Video className="mx-auto h-12 w-12 text-muted-foreground" />
                        <p className="mt-2 text-sm text-muted-foreground">
                          Session recording playback
                        </p>
                      </div>
                    </div>
                    {!isPlaying && (
                      <button
                        className="absolute inset-0 flex items-center justify-center bg-black/30"
                        onClick={() => setIsPlaying(true)}
                      >
                        <div className="flex h-16 w-16 items-center justify-center rounded-full bg-primary/90 text-primary-foreground">
                          <Play className="h-6 w-6 ml-1" />
                        </div>
                      </button>
                    )}
                  </div>
                  <div className="border-t border-border p-4">
                    <div className="flex items-center gap-4">
                      <IconButton
                        variant="ghost"
                        onClick={() => setCurrentTime(Math.max(0, currentTime - 10))}
                      >
                        <SkipBack className="h-4 w-4" />
                      </IconButton>
                      <IconButton
                        variant="default"
                        onClick={() => setIsPlaying(!isPlaying)}
                      >
                        {isPlaying ? (
                          <Pause className="h-4 w-4" />
                        ) : (
                          <Play className="h-4 w-4 ml-0.5" />
                        )}
                      </IconButton>
                      <IconButton
                        variant="ghost"
                        onClick={() =>
                          setCurrentTime(Math.min(totalVideoDuration, currentTime + 10))
                        }
                      >
                        <SkipForward className="h-4 w-4" />
                      </IconButton>

                      <div className="flex-1">
                        <div
                          className="relative h-1.5 cursor-pointer rounded-full bg-muted"
                          onClick={(e) => {
                            const rect = e.currentTarget.getBoundingClientRect();
                            const percent = (e.clientX - rect.left) / rect.width;
                            setCurrentTime(percent * totalVideoDuration);
                          }}
                        >
                          <div
                            className="absolute h-full rounded-full bg-primary"
                            style={{
                              width: `${(currentTime / totalVideoDuration) * 100}%`,
                            }}
                          />
                          {mockSubmission.violations.map((violation, i) => {
                            const timeParts = violation.timestamp.split(":");
                            const seconds =
                              parseInt(timeParts[0]) * 60 + parseInt(timeParts[1]);
                            return (
                              <div
                                key={i}
                                className="absolute top-1/2 -translate-y-1/2 h-3 w-1 rounded-full bg-destructive"
                                style={{
                                  left: `${(seconds / totalVideoDuration) * 100}%`,
                                }}
                              />
                            );
                          })}
                        </div>
                      </div>

                      <span className="text-xs text-muted-foreground min-w-[80px] text-right">
                        {formatTime(currentTime)} / {formatTime(totalVideoDuration)}
                      </span>
                    </div>
                  </div>
                </motion.div>
              )}

              {activeTab === "similarity" && (
                <motion.div
                  key="similarity"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="p-6"
                >
                  {/* Overall Similarity Score */}
                  <div className="flex items-center gap-4 rounded-lg border border-border bg-muted/50 p-4">
                    <div
                      className={`flex h-16 w-16 items-center justify-center rounded-full ${
                        mockSubmission.llmSimilarity.overall > 60
                          ? "bg-destructive/20"
                          : mockSubmission.llmSimilarity.overall > 40
                          ? "bg-yellow-500/20"
                          : "bg-emerald-500/20"
                      }`}
                    >
                      <span
                        className={`text-2xl font-bold ${
                          mockSubmission.llmSimilarity.overall > 60
                            ? "text-destructive"
                            : mockSubmission.llmSimilarity.overall > 40
                            ? "text-yellow-500"
                            : "text-emerald-500"
                        }`}
                      >
                        {mockSubmission.llmSimilarity.overall}%
                      </span>
                    </div>
                    <div>
                      <h4 className="font-semibold">Overall AI Similarity</h4>
                      <p className="text-sm text-muted-foreground">
                        Based on pattern analysis across all submitted code
                      </p>
                    </div>
                  </div>

                  {/* Heatmap Visualization */}
                  <div className="mt-6">
                    <h4 className="text-sm font-medium mb-3">
                      Code Similarity Heatmap
                    </h4>
                    <div className="grid grid-cols-3 gap-2">
                      {mockSubmission.questions.map((q, i) => (
                        <div
                          key={q.id}
                          className="rounded-lg p-4 text-center"
                          style={{
                            backgroundColor: `rgba(${
                              q.similarity > 60
                                ? "239, 68, 68"
                                : q.similarity > 40
                                ? "234, 179, 8"
                                : "34, 197, 94"
                            }, ${q.similarity / 100 * 0.3 + 0.1})`,
                          }}
                        >
                          <p className="text-xs text-muted-foreground mb-1">Q{i + 1}</p>
                          <p className="text-lg font-bold">{q.similarity}%</p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Source Analysis */}
                  <div className="mt-6">
                    <h4 className="text-sm font-medium mb-3">
                      Detected Patterns
                    </h4>
                    <div className="space-y-3">
                      {mockSubmission.llmSimilarity.sources.map((source, i) => (
                        <div
                          key={i}
                          className="rounded-lg border border-border p-4"
                        >
                          <div className="flex items-center justify-between">
                            <span className="font-medium text-sm">{source.type}</span>
                            <span
                              className={`text-sm font-bold ${
                                source.similarity > 60
                                  ? "text-destructive"
                                  : source.similarity > 40
                                  ? "text-yellow-500"
                                  : "text-emerald-500"
                              }`}
                            >
                              {source.similarity}%
                            </span>
                          </div>
                          <p className="mt-2 text-xs text-muted-foreground">
                            {source.snippet}
                          </p>
                          <div className="mt-2 h-1.5 rounded-full bg-muted">
                            <div
                              className={`h-full rounded-full ${
                                source.similarity > 60
                                  ? "bg-destructive"
                                  : source.similarity > 40
                                  ? "bg-yellow-500"
                                  : "bg-emerald-500"
                              }`}
                              style={{ width: `${source.similarity}%` }}
                            />
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        </div>

        {/* Violation Details */}
        <motion.div
          className="mt-8"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
        >
          <h2 className="text-lg font-semibold">Violation Details</h2>
          <div className="mt-4 rounded-xl border border-border bg-card overflow-hidden">
            <table className="w-full">
              <thead>
                <tr className="border-b border-border bg-muted/50">
                  <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-muted-foreground">
                    Type
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-muted-foreground">
                    Description
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-muted-foreground">
                    Timestamp
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-muted-foreground">
                    Severity
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium uppercase tracking-wider text-muted-foreground">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {mockSubmission.violations.map((violation, i) => (
                  <tr key={i} className="hover:bg-muted/30">
                    <td className="px-6 py-4">
                      <span className="font-medium">
                        {violation.type
                          .split("_")
                          .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
                          .join(" ")}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-muted-foreground">
                      {violation.description}
                    </td>
                    <td className="px-6 py-4 font-mono text-sm">
                      {violation.timestamp}
                    </td>
                    <td className="px-6 py-4">
                      <span
                        className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${
                          severityColors[violation.severity]
                        }`}
                      >
                        {violation.severity.charAt(0).toUpperCase() +
                          violation.severity.slice(1)}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <button
                        className="text-sm text-primary hover:underline"
                        onClick={() => {
                          const timeParts = violation.timestamp.split(":");
                          const seconds =
                            parseInt(timeParts[0]) * 60 + parseInt(timeParts[1]);
                          setCurrentTime(seconds);
                          setActiveTab("video");
                        }}
                      >
                        View Recording
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </motion.div>

        {/* Add Note Section */}
        <motion.div
          className="mt-8 rounded-xl border border-border bg-card p-6"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.9 }}
        >
          <h3 className="font-semibold">Add Note</h3>
          <textarea
            className="mt-3 w-full rounded-lg border border-input bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-ring resize-none"
            rows={3}
            placeholder="Add internal notes about this candidate..."
          />
          <div className="mt-3 flex justify-end">
            <AnimatedButton
              variant="default"
              size="sm"
              icon={<MessageSquare className="h-4 w-4" />}
            >
              Add Note
            </AnimatedButton>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
